export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const FETCHED_DATA_SUCCESSFULLY = 'FETCHED_DATA_SUCCESSFULLY';
export const SET_EDIT_MODE = 'SET_EDIT_MODE';
export const UPDATE_TODO_ITEM = 'UPDATE_TODO_ITEM';
export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM';
