export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const SAVE_DATA = 'SAVE_DATA';
export const SAVING_DATA_FAILED = 'SAVING_DATA_FAILED';
export const SAVED_DATA_SUCCESSFULLY = 'SAVED_DATA_SUCCESSFULLY';