export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const SAVE_DATA = 'SAVE_DATA';
export const SAVING_DATA_FAILED = 'SAVING_DATA_FAILED';
export const SAVED_DATA_SUCCESSFULLY = 'SAVED_DATA_SUCCESSFULLY';
export const FETCHED_DATA_SUCCESSFULLY = 'FETCHED_DATA_SUCCESSFULLY';
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX';
export const UPDATE_TODO_ITEM = 'UPDATE_TODO_ITEM';
export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM';